# 根据动画实测，总用时刚好就是闪反用时极限，不打断时间就是极限无敌时间,精准到0.1秒
operations:
  - op_name: "按键-闪避"
    post_delay: 0.2
  - op_name: "按键-普通攻击"
    post_delay: 0.4
    repeat: 8
  - op_name: "按键-普通攻击"
    post_delay: 0.4
    repeat: 8
