operations:
<<<<<<< HEAD

=======
>>>>>>> a004323 (伊芙琳长按时不打断技能)
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2.6
  - op_name: "按键-普通攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.6
  - op_name: "按键-普通攻击-松开"
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "清除状态"
    data: [ "伊芙琳-缠绕禁制" ]
  - op_name: "设置状态"
    data: [ "自定义-速切结束" ]
  - op_name: "等待秒数"
    seconds: 1.5