operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1
  - op_name: "按键-特殊攻击"
    post_delay: 0.2
    repeat: 2
  - op_name: "设置状态"
    data: [ "自定义-速切结束" ]
  - op_name: "等待秒数"
    seconds: 0.6
