#根据动画实测
operations:
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 43
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: -1
  - op_name: "设置状态"
    data: ["自定义-速切结束"]
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 10
  - op_name: "清除状态"
    state: "自定义-动作不打断"
