# 负责闪A切人A 普攻后摇等待时间各角色不同 由后续动作控制

# thx 4 all committer，love u all

operations:
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-闪避"
    post_delay: 0.1
  - op_name: "按键-普通攻击"
    post_delay: 0.05
  - op_name: "按键-切换角色-下一个"
    post_delay: 0.1
