operations:
  - op_name: "按键-特殊攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.5
  # 前0.5秒没有无敌
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2.9
  # 一段蓄力5秒
  - op_name: "等待秒数"
    seconds: 0.5

  # 坐箱0.4秒
  - op_name: "按键-移动-前-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-移动-前-松开"

  - op_name: "按键-移动-左-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-移动-左-松开"

  - op_name: "按键-移动-后-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-移动-后-松开"

  - op_name: "按键-移动-右-按下"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-移动-右-松开"

  # 坐箱蓄力2秒
  - op_name: "等待秒数"
    seconds: 2
  - op_name: "按键-特殊攻击-松开"