operations:
  - op_name: "设置状态"
    state: "自定义-不使用快速支援"
    seconds: 5
  - operation_template: "通用-闪避-前"
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 6
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 4
  - op_name: "设置状态"
    state: "自定义-妮可-能量场"
    seconds: 4
  - op_name: "清除状态"
    state: "自定义-不使用快速支援"

  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 7