# 根据动画实测
operations:
  - op_name: "按键-普通攻击"
    way: "按下"
    press: 0.8
  - op_name: "按键-普通攻击"
    way: "松开"
  - op_name: "等待秒数"
    seconds: 0.1

  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 15