#根据动画实测
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2.2
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 4
  - op_name: "按键-特殊攻击"
    way: "按下"
  - op_name: "等待秒数"
    seconds: 1.8
  - op_name: "按键-特殊攻击"
    way: "松开"
