# 首次需接蓄力A或闪A一次，后续可循环触发；example：朱鸢-清空弹匣
operations:
  - op_name: "按键-普通攻击-按下"
    data: [ "0.6" ]
  - op_name: "按键-普通攻击-按下"
    data: [ "0.5" ]
  - op_name: "按键-普通攻击-按下"
    data: [ "0.5" ]
  - op_name: "等待秒数"
    data: [ "1" ]
