# 根据动画实测
operations:
  - op_name: "按键-特殊攻击"
    way: "松开"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "设置状态"
    state: "自定义-异常-火"
    add: 450
  - op_name: "按键-特殊攻击"
    way: "按下"
    press: 2.3

  - op_name: "按键-特殊攻击"
    way: "松开"
  - op_name: "等待秒数"
    seconds: 0.1

  - op_name: "设置状态"
    state: "自定义-柏妮思-灼烧"
  - op_name: "等待秒数"
    seconds: 0.6
