# 根据动画实测
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2
  - op_name: "按键-特殊攻击"
    way: "按下"
    press: 1
  - op_name: "设置状态"
    state: "自定义-异常-电"
    add: 103
  - op_name: "按键-特殊攻击"
    way: "松开"
  - op_name: "设置状态"
    state: "自定义-柳-森罗万象"
  - op_name: "清除状态"
    state: "自定义-柳-上弦"
  - op_name: "设置状态"
    state: "自定义-柳-下弦"
  - op_name: "等待秒数"
    seconds: 1
