#根据动画实测
operations:
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 25
  - op_name: "设置状态"
    state: "自定义-异常-电"
    add: 160
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 10
  - op_name: "按键-特殊攻击"
    post_delay: 0.5
    repeat: 2
  - op_name: "设置状态"
    state: "自定义-柳-流转"
  - op_name: "清除状态"
    state: "自定义-柳-上弦"
  - op_name: "设置状态"
    state: "自定义-柳-下弦"
