#根据动画实测
operations:
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 24
  - op_name: "按键-特殊攻击"
    post_delay: 0.2
  - op_name: "清除状态"
    state: "自定义-动作不打断"
  - op_name: "设置状态"
    state: "自定义-柳-流转"