operations:
  # 第三段普攻强化E 快速轮胎转
  - op_name: "按键-移动-左"
    way: "按下"
    post_delay: 0.05
  - op_name: "按键-闪避"
    post_delay: 0.05
  - op_name: "按键-移动-左"
    way: "松开"

  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 13
  - op_name: "按键-特殊攻击"
    way: "按下"
  - op_name: "等待秒数"
    seconds: 1.5
  - op_name: "按键-特殊攻击"
    way: "松开"
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1.8
  - op_name: "设置状态"
    state: "自定义-异常-物理"
    add: 200
  - op_name: "等待秒数"
    seconds: 1.8