# 重击穿刺后再接普攻 优先打背伤
operations:
  # 重击 接三段普攻, 不打满尽量背身E

  - op_name: "按键-普通攻击"
    way: "按下"
    press: 0.6
    post_delay: 0.4
  - op_name: "按键-普通攻击"
    way: "松开"
  - op_name: "按键-普通攻击"
    post_delay: 0.2
    repeat: 3
  - op_name: "按键-特殊攻击"
    # 预延迟防止普攻卡E
    pre_delay: 0.2
    post_delay: 0.8