operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 3
  - op_name: "设置状态"
    state: "自定义-珂蕾妲-升温"
  - op_name: "设置状态"
    data: ["自定义-速切结束"]
  - op_name: "等待秒数"
    seconds: 1.2