operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 25

  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1.5
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 15

  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 10

  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2.5
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 25
