# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-连携换人"
    seconds_add: -1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4.5
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 20
  - op_name: "等待秒数"
    seconds: 2.5