operations:
  - op_name: "按键-移动-前-按下"
    data: []
  - op_name: "等待秒数"
    data: ["0.1"]
  - op_name: "按键-闪避-按下"
    data: ["0.3"]
  - op_name: "等待秒数"
    data: ["0.1"]
  - op_name: "按键-普通攻击-按下"
    data: ["1.4"]
  - op_name: "设置状态"
    state: "自定义-动作不打断"
  - op_name: "按键-移动-前-按下"
    data: ["0.3"]
  - op_name: "清除状态"
    state: "自定义-动作不打断"
