operations:
  - op_name: "按键-特殊攻击"
    post_delay: 0.05
    repeat: 8
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 8
  # 回旋斩接切割
  - op_name: "按键-特殊攻击"
    pre_delay: 0.025
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 16
  - op_name: "按键-普通攻击"
    post_delay: 0.4
