operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2

  - op_name: "按键-特殊攻击"
    way: "松开"
  - op_name: "等待秒数"
    seconds: 0.1

  - op_name: "按键-特殊攻击"
    way: "按下"
    press: 1
  - op_name: "设置状态"
    data: ["自定义-速切结束"]
  - op_name: "等待秒数"
    seconds: 1
  - op_name: "按键-特殊攻击"
    way: "松开"
