# 根据动画实测，动画持续1秒
operations:
  # 无敌时间是1秒
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 4
  # E可以打出1200点烈霜
  - op_name: "设置状态"
    state: "自定义-异常-烈霜"
    add: 120
  - op_name: "等待秒数"
    seconds: 0.6