# 根据动画实测，总用时刚好就是用时极限，不打断时间就是极限无敌时间,精准到0.1秒
operations:
  # 无敌时间是2.7秒，这里星见雅在闪避之后是直接接上一套无敌的普攻哦
  # 如果是必然的连段，尽可能写在一切，防止延迟导致操作变形
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2.7
  - operation_template: "通用-闪避-左"
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 22
  # 闪A可以打出770点烈霜
  - op_name: "设置状态"
    state: "自定义-异常-烈霜"
    add: 77
  - op_name: "等待秒数"
    seconds: 0.5
