#根据录像数帧，2秒后可以合轴，4秒后可以打断不丢伤害
operations:
  - op_name: "设置状态"
    state: "自定义-星见雅使用过拔刀斩"
  - op_name: "设置状态"
    state: "自定义-动作不打断"
  - op_name: "按键-普通攻击"
    way: "按下"
    press: 2
  - op_name: "等待秒数"
    seconds: 2.2
  - op_name: "清除状态"
    state: "自定义-动作不打断"
  - operation_template: "雅-终结技"