# 根据动画实测，总用时刚好就是用时极限，不打断时间就是极限无敌时间, 精准到0.1秒
operations:
  - op_name: "设置状态"
    state: "自定义-连携换人"
    seconds_add: -1
  # 连携攻击无敌时间是2秒，注意这里一定要根据角色严格测定
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2
  - op_name: "等待秒数"
    seconds: 2
  # 一套连携可以打出1010点烈霜
  - op_name: "设置状态"
    state: "自定义-异常-烈霜"
    add: 101