# 根据录像数帧，2秒后可以合轴，4秒后可以打断不丢伤害
operations:
  # 参照拔刀斩和终结技
  - op_name: "设置状态"
    state: "自定义-连携换人"
    seconds_add: -1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4.2

  - op_name: "按键-普通攻击"
    way: "按下"
    press: 2.2
  - op_name: "按键-普通攻击"
    way: "松开"
  - op_name: "设置状态"
    state: "自定义-异常-烈霜"
    add: 119
  - op_name: "等待秒数"
    seconds: 2
  - operation_template: "雅-终结技"