#根据录像数帧，2秒后可以合轴，4秒后可以打断不丢伤害
operations:
  #这里代表拔刀斩无敌时间是4.2秒
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4.2

  - op_name: "按键-普通攻击"
    way: "按下"
    press: 2.2
  - op_name: "按键-普通攻击"
    way: "松开"
  #长按结束，说明确凿无误地必然会打出去，这个时候就可以给烈霜值加上1190
  - op_name: "设置状态"
    state: "自定义-异常-烈霜"
    add: 119
  #这里代表可以合轴，在这里设置这个状态，就会触发速切触发器，尝试进行切人
  - op_name: "设置状态"
    data: ["自定义-速切结束"]
  - op_name: "等待秒数"
    seconds: 2
