# 根据动画实测
operations:
  # 终结技实测动作无敌时间为4.5秒
  - op_name: "设置状态"
    state: "自定义-连携换人"
    seconds_add: -1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 4.5
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 20
  # 一次终结技可以打出3090点烈霜
  - op_name: "设置状态"
    state: "自定义-异常-烈霜"
    add: 309
  - op_name: "等待秒数"
    seconds: 2.5
