# 根据动画实测，总用时刚好就是用时极限，不打断时间就是极限无敌时间,精准到0.1秒
operations:
  # 支援攻击持续2.2秒无敌时间，期间按普攻保证能打出去
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2.2
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 22
  # 一次支援可以打出780点烈霜
  - op_name: "设置状态"
    state: "自定义-异常-烈霜"
    add: 78
