#根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 0.4
  - op_name: "按键-特殊攻击"
    post_delay: 0.1
    repeat: 4
  - op_name: "设置状态"
    state: "自定义-零号安比-白雷"
    add: -100

