# 根据动画实测，动画持续2秒
operations:
  - operation_template: "通用-闪避-左"
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1
  - op_name: "设置状态"
    state: "自定义-零号安比-白雷"
    add: 150
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 10