# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 1.2
  - op_name: "清除状态"
    state: "自定义-零号安比-白雷"
  - op_name: "设置状态"
    state: "自定义-零号安比-白雷"
    add: 300
  - op_name: "按键-特殊攻击-按下"
  - op_name: "等待秒数"
    seconds: 0.5
  - op_name: "设置状态"
    data: ["自定义-速切结束"]
  - op_name: "等待秒数"
    seconds: 0.7
  - op_name: "按键-特殊攻击-松开"
