# 根据动画实测，动画持续2秒
operations:
  - op_name: "设置状态"
    state: "自定义-连携换人"
    seconds_add: -1
  - op_name: "设置状态"
    state: "自定义-动作不打断"
    seconds: 2.4
  - op_name: "按键-普通攻击"
    post_delay: 0.1
    repeat: 24
  - op_name: "设置状态"
    state: "自定义-零号安比-白雷"
    add: 70