#根据动画实测，总用时刚好就是用时极限，不打断时间就是极限无敌时间,精准到0.1秒
operations:
  - op_name: "设置状态"
    state: "自定义-露西-加油"
  - op_name: "按键-特殊攻击"
    way: "松开"
  - op_name: "等待秒数"
    seconds: 0.1
  - op_name: "按键-特殊攻击"
    way: "按下"
    press: 0.4
  - op_name: "设置状态"
    data: ["自定义-速切结束"]
  - op_name: "按键-特殊攻击"
    way: "松开"
  - op_name: "等待秒数"
    seconds: 0.6
