#根据动画实测，动画持续5秒,第三秒开始可以切人
operations:
  - op_name: "设置状态"
    state: "自定义-动作不打断"
  - op_name: "按键-终结技"
    post_delay: 0.1
    repeat: 30
  - op_name: "等待秒数"
    seconds: 1.7
  - op_name: "清除状态"
    state: "自定义-动作不打断"
  - op_name: "设置状态"
    state: "自定义-柳-流转"