sub_dir: agent_state
template_id: soukaku_3_2
template_name: 角色状态-苍角-32
template_shape: polygon
auto_mask: true
point_list:
- 582, 92
- 592, 92
- 592, 95
- 599, 95
- 599, 92
- 609, 92
- 609, 95
- 616, 95
- 616, 92
- 626, 92
- 626, 95
- 626, 103
- 616, 103
- 616, 95
- 609, 95
- 609, 103
- 599, 103
- 599, 95
- 592, 95
- 592, 103
- 582, 103