sub_dir: agent_state
template_id: soukaku_2_2
template_name: 角色状态-苍角-22
template_shape: polygon
auto_mask: true
point_list:
- 616, 92
- 626, 92
- 626, 95
- 633, 95
- 633, 92
- 643, 92
- 643, 95
- 650, 95
- 650, 92
- 660, 92
- 660, 95
- 660, 103
- 650, 103
- 650, 95
- 643, 95
- 643, 103
- 633, 103
- 633, 95
- 626, 95
- 626, 103
- 616, 103