sub_dir: agent_state
template_id: zhu_yuan_3_1
template_name: 角色状态-朱鸢-31
template_shape: quadrilateral
auto_mask: true
point_list:
- 145, 114
- 153, 138
- 200, 138
- 208, 114
emulator_point_list:
- 168, 139
- 176, 168
- 236, 168
- 245, 139
