# 黄光时 尽量使用双反 并优先切换到强攻角色 需额外处理兜底情况
# 负责闪A切人A 普攻后摇等待时间各角色不同 由后续动作控制
handlers:
  - states: "[后台-2-命破]"
    operations:
      - op_name: "按键-切换角色-上一个"
      - op_name: "设置状态"
        data: ["自定义-黄光切人"]
  - states: "[后台-1-命破]"
    operations:
      - op_name: "按键-切换角色-下一个"
      - op_name: "设置状态"
        data: ["自定义-黄光切人"]