#有特殊BUFF的才加
handlers:
  - states: "[前台-柏妮思] & [柏妮思-能量]{40,120}"
    operations:
    - operation_template: "柏妮思-格挡攻击"
    - operation_template: "柏妮思-直接长按特殊攻击"
  - states: "[前台-柏妮思] & [柏妮思-能量]{0,40}"
    operations:
    - operation_template: "柏妮思-格挡攻击"

  - states: "[前台-柳]"
    operations:
    - operation_template: "柳-格挡攻击"
  - states: ""
    operations:
    - op_name: "按键-普通攻击"
      post_delay: 0.2
      repeat: 10

