# 格莉丝不需要额外的强化E触发, 她永远遵循3A1E的策略, 先普通攻击, 然后是特殊攻击,最后是终结技.

handlers:
  - states: "[前台-格莉丝]"
    sub_handlers:
    - states: "[按键可用-终结技]"
      operations:
        - op_name: "按键-终结技"
          data: []
        - op_name: "等待秒数"
          data: ["3"]
    # - states: "[按键可用-特殊攻击]"
    #   operations:
    #     - op_name: "按键-特殊攻击"
    #       data: []
    #     - op_name: "等待秒数"
    #       data: ["0.3"]
    - states: ""
      operations:
        - op_name: "按键-普通攻击"
          data: []
        - op_name: "等待秒数"
          data: [ "0.3" ]
        - op_name: "按键-普通攻击"
          data: []
        - op_name: "等待秒数"
          data: [ "0.5" ]
        - op_name: "按键-普通攻击"
          data: []
        - op_name: "等待秒数"
          data: [ "0.5" ]
        - op_name: "按键-特殊攻击"
          data: []
        - op_name: "等待秒数"
          data: [ "0.6" ]
