description: "希望站场角色可以流畅连贯完成动作"
handlers:
  - state_template: "站场模板-11号"
  - state_template: "站场模板-青衣"
  - state_template: "站场模板-安比"
  - state_template: "站场模板-莱卡恩"
  - state_template: "站场模板-妮可"
  - state_template: "站场模板-朱鸢"
  - state_template: "站场模板-可琳"
  - state_template: "站场模板-格莉丝"
  - state_template: "站场模板-派派"
  - state_template: "站场模板-雅"
  - state_template: "站场模板-柳"
  - state_template: "站场模板-简"
  - state_template: "站场模板-悠真"
  - state_template: "站场模板-通用"
