handlers:
  - states: "[前台-可琳]"
    sub_handlers:
      - states: ""
        operations:
          - op_name: "按键-移动-前"
            post_delay: 0.1
          - op_name: "按键-闪避"
            post_delay: 0.1
          - op_name: "按键-普通攻击"
            post_delay: 0.1
          - op_name: "按键-普通攻击"
            post_delay: 0.1
          - op_name: "按键-普通攻击"
            post_delay: 0.1
          - op_name: "按键-普通攻击"
            post_delay: 0.1
          - op_name: "按键-普通攻击"
            post_delay: 0.1
          - op_name: "按键-普通攻击"
            post_delay: 0.1
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
          - op_name: "按键-移动-前"
            post_delay: 0.1
          - op_name: "按键-闪避"
            post_delay: 0.1
