# 朱鸢站场的主要动作
main_qingyi: &main
  - states: "[前台-青衣]"
    sub_states:

    # 连续普攻一段时间就往前闪一下 防止打不到远程敌人
    - states: "[自定义-青衣-普攻次数]{40, 999}"
      operations:
        - operation_template: "通用-闪避-前"
        - op_name: "清除状态"
          state:  "自定义-青衣-普攻次数"

    - states: "[按键可用-终结技]"
      operations:
        - op_name: "按键-终结技"
          post_delay: 4
        - op_name: "清除状态"
          state:  "自定义-青衣-普攻次数"

    - states: "[青衣-电压, 0, 999]{75, 101}"
      operations:
        - op_name: "设置状态"
          state: "自定义-动作不打断"
          value: 1
        - op_name: "按键-普通攻击"
          way: "按下"
          press: 2.5
          post_delay: 1
        - op_name: "清除状态"
          state: "自定义-动作不打断"
        - op_name: "清除状态"
          state:  "自定义-青衣-普攻次数"

    - states: "[按键可用-特殊攻击]"
      operations:
        - op_name: "按键-闪避"
          post_delay: 0.1
        - op_name: "按键-特殊攻击"
          post_delay: 1.5
        - op_name: "清除状态"
          state:  "自定义-青衣-普攻次数"

    - states: ""
      operations:
      - op_name: "按键-普通攻击"
        post_delay: 0.1
      - op_name: "设置状态"
        state: "自定义-青衣-普攻次数"
        add: 1


handlers:
  - states: "[前台-青衣]"
    sub_states:
    - states: "[自定义-黄光切人]"
      operations:
        - op_name: "按键-普通攻击"
          post_delay: 0.2
          repeat: 8
        - op_name: "清除状态"
          state: "自定义-黄光切人"

    - states: "[自定义-红光闪避]"
      operations:
        - op_name: "等待秒数"
          seconds: 1.2
        - op_name: "清除状态"
          state:  "自定义-红光闪避"
        - op_name: "清除状态"
          state:  "自定义-青衣-普攻次数"

    - states: "[自定义-连携换人]"
      operations:
        - op_name: "等待秒数"
          seconds: 2
        - op_name: "清除状态"
          state:  "自定义-连携换人"
        - op_name: "清除状态"
          state:  "自定义-青衣-普攻次数"

    - states: "[自定义-快速支援换人]"
      operations:
        - op_name: "等待秒数"
          data: [ "0.5" ]
        - op_name: "清除状态"
          data: [ "自定义-快速支援换人" ]

    - states: "[自定义-血量扣减]"
      operations:
        - op_name: "按键-闪避"
          pre_delay: 0.8
          post_delay: 0.5
        - op_name: "按键-普通攻击"
          post_delay: 0.5
        - op_name: "清除状态"
          data: [ "自定义-血量扣减" ]

    - states: ""
      sub_states: *main
