# 根据情况切人，防止过度切人
handlers:
  - states: "![自定义-动作不打断, 0, 30]"
    sub_handlers:
      # 星见雅 有6豆就切过去
      - states: "[雅-落霜]{6, 6} & ![前台-雅]"
        operations:
          - op_name: "按键-切换角色"
            agent_name: "雅"
            
      - states: "[自定义-速切结束,0,12]"
        sub_handlers:
          - states: "[凯撒-能量]{60, 120} & [自定义-血量扣减,0,1]"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "凯撒"

          - states: "[莱卡恩-能量]{60, 120}"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "莱卡恩"

          - states: "[苍角-能量]{90, 120} & ![自定义-苍角-展旗,0,30]"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "苍角"

          - states: "[丽娜-能量]{60, 120}"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "丽娜"

          - states: "([柏妮思-能量]{60, 120} & [柏妮思-燃点]{0,20}) | (![自定义-柏妮思燃点,0,12] & [柏妮思-燃点]{60,100})"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "柏妮思"

          - states: "[莱特-能量]{80, 120} | ![自定义-莱特-BUFF, 0, 15] & [莱特-士气]{80, 100}"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "莱特"

          - states: "( [赛斯-能量]{85, 121} | [赛斯-意气]{95, 101} ) & ![自定义-赛斯-意气风发,0,20]"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "赛斯"

          - states: "[露西-能量]{60, 120} & ![自定义-露西-加油,0,30]"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "露西"

          - states: "[妮可-能量]{60, 120}"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "妮可"

          - states: "[柳-能量]{80, 120}"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "柳"

          - states: "[本-能量]{80, 120} & ![自定义-本-守卫,0,30]"
            operations:
              - op_name: "按键-切换角色"
                agent_name: "本"
