# 连携后摇等待时间各角色不同 由后续动作控制
handlers:
  - states: "[连携技-1-命破]"
    operations:
      - op_name: "按键-连携技-左"
      - op_name: "设置状态"
        state: "自定义-连携换人"
  - states: "[连携技-2-命破]"
    operations:
      - op_name: "按键-连携技-右"
      - op_name: "设置状态"
        state: "自定义-连携换人"