# 闪避普攻 普攻后摇等待时间各角色不同 由后续动作控制
handlers:
  - states: "[自定义-连携跳过, 0, 1]"
    sub_handlers:
      - state_template: "连携模板-跳过"

  - states: " [前台-苍角] & [自定义-连携换人, 0, 3] "
    sub_handlers:
      - state_template: "连携模板-强攻"
      - state_template: "连携模板-异常"
      - state_template: "连携模板-跳过"

  - states: " [前台-强攻] & [前台-命破] & [自定义-连携换人, 0, 3] "
    sub_handlers:
      - state_template: "连携模板-支援"
      - state_template: "连携模板-命破"
      - state_template: "连携模板-强攻"
      - state_template: "连携模板-跳过"

  - states: ""
    sub_handlers:
      - state_template: "连携模板-支援"
      - state_template: "连携模板-异常"
      - state_template: "连携模板-命破"
      - state_template: "连携模板-强攻"
      - states: "![前台-强攻]"
        sub_handlers:
          - state_template: "连携模板-击破"
          - state_template: "连携模板-防护"
      - state_template: "连携模板-跳过"
