# 连携后摇等待时间各角色不同 由后续动作控制
handlers:
  # 苍角别把展旗覆盖掉了
  - states: "[连携技-1-支援] & !( [苍角-涡流,0,30]{0,1} & [连携技-1-苍角] )"
    operations:
      - op_name: "按键-连携技-左"
      - op_name: "设置状态"
        state: "自定义-连携换人"
  - states: "[连携技-2-支援] & !( [苍角-涡流,0,30]{0,1} & [连携技-2-苍角] )"
    operations:
      - op_name: "按键-连携技-右"
      - op_name: "设置状态"
        state: "自定义-连携换人"
