handlers:
  - states: "[前台-珂蕾妲]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "通用-连携攻击"
      - states: "[按键可用-终结技] & !([按键-切换角色-下一个,0,1]|[按键-切换角色-上一个,0,1]) & ![自定义-动作不打断, 0, 30]"
        operations:
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-终结技"
            post_delay: 1
            repeat: 5
          - op_name: "清除状态"
            state: "自定义-动作不打断"
      - states: "[自定义-珂蕾妲-升温,0,8] | [自定义-连携换人,0,2]"
        operations:
          - op_name: "清除状态"
            state: "自定义-珂蕾妲-升温"
          - op_name: "按键-普通攻击"
            post_delay: 0.1
            repeat: 25
      - states: "[珂蕾妲-能量]{60,120} & [按键可用-特殊攻击] & ![自定义-珂蕾妲-升温,0,8]"
        operations:
          - op_name: "设置状态"
            state: "自定义-珂蕾妲-升温"
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
            repeat: 15
      - states: "![自定义-珂蕾妲-升温,0,8]"
        operations:
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]