template_name: "速切模板-简"
handlers:
  - states: "[前台-简]"
    sub_handlers:

      #支援
      - states: "[自定义-黄光切人, 0, 2]"
        operations:
          - operation_template: "简-格挡攻击"

      #连携
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "简-连携攻击"

      #防呆
      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3])"
        operations:
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      #终结技时刻，需要注意出场第一秒可能识别错误
      - states: "[按键可用-终结技] & !([按键-切换角色-下一个,0,1]|[按键-切换角色-上一个,0,1])"
        operations:
          - operation_template: "简-终结技"

        #当前狂热心流不足50%且萨霍夫可使用则使用萨霍夫
      - states: "![简-狂热心流]{60, 101} & [简-萨霍夫跳]"
        operations:
          - operation_template: "简-长按A合轴"

      #朴实无华
      - states: "[简-能量]{60,120} & [按键可用-特殊攻击]"
        operations:
          - operation_template: "简-强化特殊攻击"

      #简6段a
      - states: "![简-能量]{60,120}"
        operations:
          - operation_template: "简-普通攻击"