template_name: "速切模板-莱卡恩"
handlers:
  - states: "[前台-莱卡恩]"
    sub_handlers:

      #支援
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"

      #连携
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "通用-连携攻击"

      #防呆
      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      #失衡时刻
      - states: "([自定义-连携换人,0,12]"
        operations:
          - operation_template: "通用-切人普通攻击"
              
      #终结技时刻，需要注意出场第一秒可能识别错误
      - states: "[莱卡恩-终结技可用]"
        operations:
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-终结技"
            post_delay: 1
            repeat: 5
          - op_name: "清除状态"
            state: "自定义-动作不打断"
            
      - states: "[莱卡恩-特殊技可用]"
        operations:
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-特殊攻击"
            way: "按下"
            press: 2.4
          - op_name: "清除状态"
            state: "自定义-动作不打断"
          - operation_template: "通用-切人普通攻击"

      - states: ""
        operations:
          - operation_template: "通用-切人普通攻击"
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]
