template_name: "速切模板-全角色"
handlers:
  # 特殊处理
  
  # 青衣大哥，就是自信，其他人怎么好意思站场的？
  - states: "[青衣-能量]{0, 120} & ![自定义-连携换人,0,12] & ![自定义-黄光切人, 0, 2] & ![前台-青衣]"
    operations:
      - op_name: "设置状态"
        data: [ "自定义-速切结束" ]

  - states: "[妮可-能量]{80, 120} & [自定义-连携换人,6,12] & ![自定义-黄光切人, 0, 2] & ![前台-妮可]"
    operations:
      - op_name: "设置状态"
        data: [ "自定义-速切结束" ]

  # 速切加增益
  - state_template: "速切模板-莱卡恩"
  - state_template: "速切模板-苍角"
  - state_template: "速切模板-格莉丝"
  - state_template: "速切模板-妮可"
  - state_template: "速切模板-猫又"
  - state_template: "速切模板-可琳"
  - state_template: "速切模板-派派"
  - state_template: "速切模板-柳"
  - state_template: "速切模板-雅"
  - state_template: "速切模板-简"
  - state_template: "速切模板-赛斯"
  - state_template: "速切模板-丽娜"
  - state_template: "速切模板-凯撒"
  - state_template: "速切模板-露西"
  - state_template: "速切模板-悠真"
  - state_template: "速切模板-11号"
  - state_template: "速切模板-本"
  - state_template: "速切模板-安比"
  - state_template: "速切模板-珂蕾妲"
  - state_template: "速切模板-柏妮思"
  - state_template: "速切模板-莱特"
  - state_template: "速切模板-朱鸢" #比站场更优
  - state_template: "速切模板-艾莲" #比站场更优
  - state_template: "速切模板-青衣"

  # 站场输出
  - state_template: "站场模板-青衣"
  - state_template: "站场模板-朱鸢"
  - state_template: "站场模板-艾莲"
    
  # 兜底情况，如果你发现角色动作不符合预期，那八成就是走到兜底了
  - state_template: "速切模板-通用"
