template_name: "速切模板-妮可"
handlers:
  - states: "[前台-妮可]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]
          - operation_template: "妮可-支援攻击"

      - states: "[自定义-连携换人,0,1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]
          - operation_template: "妮可-连携攻击"
          - op_name: "设置状态"
            state: "自定义-妮可-能量场"
            seconds: 0
      #防呆
      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]

      - states: "[妮可-终结技可用]"
        operations:
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-终结技"
            post_delay: 1
            repeat: 2
          - op_name: "设置状态"
            state: "自定义-妮可-能量场"
            seconds: -5
          - op_name: "清除状态"
            state_list: ["自定义-动作不打断"]
          - op_name: "设置状态"
            data: ["自定义-速切结束"]

      #失衡时刻
      - states: "[自定义-连携换人,0,12]"
        sub_handlers:
          - states: "[妮可-特殊技可用]"
            operations:
              - op_name: "按键-特殊攻击"
                post_delay: 0.2
                repeat: 4
              - op_name: "设置状态"
                state: "自定义-妮可-能量场"
                seconds: -2.2
              - op_name: "设置状态"
                data: ["自定义-速切结束"]

      - states: "[妮可-特殊技可用]"
        operations:
          - operation_template: "妮可-蓄力坐箱炮"
          - op_name: "设置状态"
            state: "自定义-妮可-能量场"
            seconds: -4
          - op_name: "设置状态"
            data: ["自定义-速切结束"]

      - states: ""
        operations:
          - op_name: "按键-普通攻击"
            post_delay: 0.1
            repeat: 25
          - op_name: "设置状态"
            data: ["自定义-速切结束"]
