template_name: "速切模板-猫又"
handlers:
  - states: "[前台-猫又]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"

      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "通用-连携攻击"

      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      #失衡时刻
      - states: "[自定义-连携换人,0,12]"
        sub_handlers:
            #失衡的时候就不用考虑这么多了，射吧
          - states: "[按键可用-终结技]"
            operations:
            - op_name: "设置状态"
              state: "自定义-动作不打断"
            - op_name: "按键-终结技"
              post_delay: 1
              repeat: 2
            - op_name: "清除状态"
              state: "自定义-动作不打断"
          #朴实无华
          - states: "[按键可用-特殊攻击]"
            operations:
            - op_name: "设置状态"
              state: "自定义-动作不打断"
            - op_name: "按键-特殊攻击"
              post_delay: 0.3
              repeat: 2
            - op_name: "清除状态"
              state: "自定义-动作不打断"

          - states: ""
            operations:
              # 重击 接三段普攻, 不打满尽量背身E
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 25

      #合轴时刻      
      - states: "![按键-切换角色-下一个,0,12] & ![按键-切换角色-上一个,0,12] &![自定义-速切结束]"
        operations:
          - operation_template: "通用-切人普通攻击"

      - states: "[按键可用-终结技] & !([按键-切换角色-下一个,0,1]|[按键-切换角色-上一个,0,1]) & ![自定义-动作不打断, 0, 30]"
        operations:
          - op_name: "按键-终结技"
            data: []
          - op_name: "等待秒数"
            data: ["3"]

      - states: "[猫又-能量]{40,120} & [按键可用-特殊攻击]"
        operations:
          - op_name: "按键-普通攻击"
            post_delay: 0.1
            repeat: 25
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-特殊攻击"
            post_delay: 0.3
            repeat: 2
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      - states: "![猫又-能量]{40,120}"
        operations:
          # 重击 接三段普攻, 不打满尽量背身E
          - op_name: "按键-普通攻击"
            post_delay: 0.1
            repeat: 50
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]
