template_name: "速切模板-通用"
handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "通用-连携攻击"

      - states: "([按键-切换角色-下一个,0,1]|[按键-切换角色-上一个,0,1]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      #合轴时刻      
      - states: "![按键-切换角色-下一个,0,12] & ![按键-切换角色-上一个,0,12] &![自定义-速切结束]"
        operations:
          - operation_template: "通用-切人普通攻击"

      #失衡时刻
      - states: "[自定义-连携换人,0,12]"
        sub_handlers:
            #失衡的时候就不用考虑这么多了，射吧
          - states: "[按键可用-终结技]"
            operations:
            - op_name: "设置状态"
              state: "自定义-动作不打断"
            - op_name: "按键-终结技"
              post_delay: 2
              repeat: 2
            - op_name: "清除状态"
              state: "自定义-动作不打断"
          #朴实无华
          - states: "[按键可用-特殊攻击]"
            operations:
            - op_name: "设置状态"
              state: "自定义-动作不打断"
            - op_name: "按键-特殊攻击"
              post_delay: 0.3
              repeat: 2
            - op_name: "清除状态"
              state: "自定义-动作不打断"

          - states: "![按键可用-特殊攻击] & ![按键可用-终结技]"
            operations:
              # 重击 接三段普攻, 不打满尽量背身E
              - op_name: "按键-普通攻击"
                post_delay: 0.1
                repeat: 25

      - states: "![自定义-连携换人,0,12]"
        sub_handlers:
        - states: " [按键可用-终结技] & !([按键-切换角色-下一个,0,1] | [按键-切换角色-上一个,0,1]) & ![自定义-动作不打断, 0, 30] & !( [前台-强攻] & ( [后台-1-击破] | [后台-2-击破] ) )"
          operations:
            - op_name: "设置状态"
              state: "自定义-动作不打断"
            - op_name: "按键-终结技"
              post_delay: 2
              repeat: 2
            - op_name: "清除状态"
              state: "自定义-动作不打断"
        - states: "[按键可用-特殊攻击] & [前台-能量]{100, 120}"
          operations:
            - op_name: "按键-特殊攻击"
              post_delay: 0.3
              repeat: 2
            - op_name: "设置状态"
              data: [ "自定义-速切结束" ]
        - states: "![按键可用-特殊攻击] & ![按键可用-终结技]"
          operations:
            - op_name: "按键-普通攻击"
              post_delay: 0.1
              repeat: 25
            - op_name: "设置状态"
              data: [ "自定义-速切结束" ]
