template_name: "速切模板-全角色"
handlers:
  - state_template: "速切模板-莱卡恩"
  - state_template: "速切模板-苍角"
  - state_template: "速切模板-格莉丝"
  - state_template: "速切模板-妮可"
  - state_template: "速切模板-猫又"
  - state_template: "速切模板-通用"
