template_name: "速切模板-柳"
handlers:
  - states: "[前台-柳]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "柳-连携攻击"

      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      - states: "[柳-能量]{40,120} & [按键可用-特殊攻击]"
        operations:
          - operation_template: "柳-强化特殊攻击"
          - op_name: "设置状态"
            state: "自定义-柳-月华流转"

      - states: "[按键可用-终结技] & !([按键-切换角色-下一个,0,1]|[按键-切换角色-上一个,0,1]) & ![自定义-动作不打断,0,30]"
        operations:
          - operation_template: "柳-终结技"
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]

      - states: "[自定义-柳-月华流转, 0, 6]"
        operations:
          - op_name: "清除状态"
            state: "自定义-柳-月华流转"
          - operation_template: "柳-普通攻击合轴"

      - states: "[自定义-柳-流转,0,2] | [自定义-柳-森罗万象, 0, 15] | [自定义-快速支援换人,0,1]"
        operations:
          - operation_template: "柳-流转攻击"

      - states: "![柳-能量]{40,120}"
        operations:
          - operation_template: "柳-普通攻击"