template_name: "速切模板-派派"
handlers:
  - states: "[前台-派派]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "通用-连携攻击"

      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      - states: "[按键可用-终结技] & !([按键-切换角色-下一个,0,1]|[按键-切换角色-上一个,0,1]) & ![自定义-动作不打断, 0, 30]"
        operations:
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-终结技"
            post_delay: 3
            repeat: 2
          - op_name: "清除状态"
            state: "自定义-动作不打断"
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]
    #转就完事
      - states: "[派派-能量]{60,120} & [按键可用-特殊攻击] & ![自定义-动作不打断]"
        operations:
          - op_name: "按键-普通攻击"
            post_delay: 0.6
            repeat: 2
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-移动-前"
            way: "按下"
          - op_name: "按键-特殊攻击"
            way: "按下"
            press: 0.8
            repeat: 5
          - op_name: "清除状态"
            state: "自定义-动作不打断"
          - op_name: "按键-特殊攻击"
            way: "松开"
          - op_name: "按键-移动-前"
            way: "松开"
            post_delay: 0.8
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]
      #派派2a
      - states: "[派派-能量]{0,60}"
        operations:
          - op_name: "按键-普通攻击"
            post_delay: 0.6
            repeat: 2
          - op_name: "按键-移动-前"
            way: "按下"
          - op_name: "按键-特殊攻击"
            way: "按下"
            press: 0.8
            repeat: 5
          - op_name: "按键-特殊攻击"
            way: "松开"
          - op_name: "按键-移动-前"
            way: "松开"
            post_delay: 0.4
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]