template_name: "速切模板-苍角"
handlers:
  - states: "[前台-苍角]"
    sub_states:
    - states: "[按键可用-特殊攻击]"
      operations:
        - op_name: "按键-特殊攻击"
          data: []
        - op_name: "等待秒数"
          data: [ "0.2" ]
        - op_name: "按键-特殊攻击-按下"
          data: [ "0.6" ]
        - op_name: "设置状态"
          data: [ "自定义-速切结束" ]
    - states: ""
      operations:
        - op_name: "按键-普通攻击"
          data: []
        - op_name: "等待秒数"
          data: [ "0.1" ]
        - op_name: "设置状态"
          data: [ "自定义-速切结束" ]
