template_name: "速切模板-青衣"
handlers:
  - states: "[前台-青衣]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]
          - operation_template: "青衣-支援攻击"

      - states: "[自定义-连携换人,0,1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]
          - operation_template: "通用-连携攻击"

      #防呆
      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]

      - states: "[青衣-电压]{80, 101}"
        operations:
          - operation_template: "青衣-醉花云月转"

      - states: "[青衣-终结技可用]"
        operations:
          - operation_template: "通用-闪避-前"
          - operation_template: "青衣-终结技"

      - states: "[青衣-特殊技可用]"
        operations:
          - operation_template: "通用-闪避-前"
          - operation_template: "青衣-特殊攻击接普通攻击"

      - states: "[青衣-电压]{0, 90}"
        operations:
          - operation_template: "通用-闪避-前"
          - operation_template: "青衣-普通攻击"
