handlers:
  - states: "[前台-雅]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "通用-连携攻击"
      - states: "[按键-切换角色-下一个,0,0.4]"
        operations:
          - op_name: "清除状态"
            state: "自定义-星见雅使用过拔刀斩"
      - states: "[雅-落霜]{6, 6}"
        operations:
          - operation_template: "雅-拔刀斩"
      - states: "[按键可用-终结技] & !([按键-切换角色-下一个,0,1]|[按键-切换角色-上一个,0,1]) & ![自定义-星见雅使用过拔刀斩, 0, 5] & [雅-落霜]{0, 3}"
        operations:
          - operation_template: "雅-终结技"
      - states: "[雅-能量]{40,120} & [按键可用-特殊攻击]"
        operations:
          - operation_template: "雅-特殊攻击"
      # 普通攻击
      - states: "![雅-能量]{40,120}"
        operations:
          - operation_template: "雅-普通攻击"