template_name: "速切模板-全角色"
handlers:
  # 每个角色一个模板，然后就可以进行
  - state_template: "速切模板-莱卡恩"
  - state_template: "速切模板-苍角"
  - state_template: "速切模板-妮可"
  - state_template: "速切模板-猫又"
  - state_template: "速切模板-可琳"
  - state_template: "速切模板-派派"
  - state_template: "速切模板-柳"
  - state_template: "速切模板-雅"
  - state_template: "速切模板-简"
  - state_template: "速切模板-赛斯"
  - state_template: "速切模板-丽娜"
  - state_template: "速切模板-凯撒"
  - state_template: "速切模板-露西"
  - state_template: "速切模板-悠真"
  - state_template: "速切模板-11号"
  - state_template: "速切模板-安比"
  - state_template: "速切模板-珂蕾妲"
  - state_template: "速切模板-柏妮思"
  - state_template: "速切模板-莱特"
  - state_template: "速切模板-朱鸢"
  - state_template: "速切模板-艾莲"
  - state_template: "速切模板-青衣"
  - state_template: "速切模板-本"
  - state_template: "速切模板-比利"
  - state_template: "速切模板-安东"
  - state_template: "速切模板-格莉丝"
  - state_template: "速切模板-耀嘉音"
  - state_template: "速切模板-伊芙琳"
  - state_template: "速切模板-零号安比"
  - state_template: "速切模板-扳机"
  - state_template: "速切模板-波可娜"
  - state_template: "速切模板-薇薇安"
  - state_template: "速切模板-仪玄"
  - state_template: "速切模板-潘引壶"
  - state_template: "速切模板-雨果"
  # 下面是缺省值，如果有上面没有的角色会走下面，一般情况下最好不要有，否则可能会因为识别不到角色而进行错误的动作

  # 如果需要新增角色，就新增一行，按照通用模板写一个新的速切模板，打开【速切模板-通用】，按照里面的说明新建模板
  # 比如需要新建一个角色耀嘉音，就新增一行 - state_template: "速切模板-耀嘉音" ，并且新建一个文件 "速切模板-耀嘉音.sample.yml"
  - state_template: "速切模板-通用"

  # 更加契合角色的模板，可以参考【速切模板-艾莲】，【速切模板-雅】是怎么写的

  # 动作模板也可以参考一下【雅】是怎么写的
