template_name: "速切模板-珂蕾妲"
handlers:
  - states: "[前台-珂蕾妲]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]
          - operation_template: "珂蕾妲-支援攻击"

      - states: "[自定义-连携换人,0,1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]
          - operation_template: "通用-连携攻击"
          - op_name: "设置状态"
            state: "自定义-珂蕾妲-升温"

      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state_list: ["自定义-速切结束", "自定义-动作不打断"]

      - states: "[珂蕾妲-终结技可用] & ![自定义-连携换人,0,12]"
        operations:
          - op_name: "设置状态"
            state: "自定义-珂蕾妲-升温"
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-终结技"
            post_delay: 1
            repeat: 5
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      #补一个升温马上离开
      - states: "[珂蕾妲-特殊技可用] & ![自定义-珂蕾妲-升温,0,8]"
        operations:
          - operation_template: "珂蕾妲-特殊技合轴"

      #快乐连招
      - states: "[珂蕾妲-特殊技可用] & [自定义-珂蕾妲-升温,0,8]"
        operations:
          - op_name: "清除状态"
            state: "自定义-珂蕾妲-升温"
          - operation_template: "珂蕾妲-强化普攻接特殊技"
          - op_name: "设置状态"
            state: "自定义-珂蕾妲-升温"

      #快乐合轴
      - states: "![珂蕾妲-特殊技可用] & [自定义-珂蕾妲-升温,0,8]"
        operations:
          - op_name: "清除状态"
            state: "自定义-珂蕾妲-升温"
          - operation_template: "珂蕾妲-强化普攻接特殊技合轴"

      - states: "![自定义-珂蕾妲-升温,0,8]"
        operations:
          - operation_template: "通用-切人普通攻击"
