#红光青衣放开左键就行了
handlers:
  - states: "[前台-青衣]"
    sub_handlers:
    - states: "[自定义-青衣-醉花云月转,0.5,2]"
      operations:
      - op_name: "设置状态"
        state: "自定义-动作不打断"
      - op_name: "按键-普通攻击"
        post_delay: 0.1
        repeat: 12
      - op_name: "清除状态"
        state: "自定义-动作不打断"


    - states: ""
      operations:
      - op_name: "设置状态"
        state: "自定义-动作不打断"
      - op_name: "按键-闪避"
        post_delay: 0.2
      - op_name: "按键-普通攻击"
        post_delay: 0.1
        repeat: 10
      - op_name: "清除状态"
        state: "自定义-动作不打断"
      - op_name: "按键-普通攻击"
        post_delay: 0.1
        repeat: 18
      - op_name: "设置状态"
        state: "自定义-动作不打断"
      - op_name: "等待秒数"
        seconds: 1.2
      - op_name: "清除状态"
        state: "自定义-动作不打断"