template_name: "速切模板-雅"
handlers:
  - states: "[前台-雅]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "通用-连携攻击"
      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state: "自定义-动作不打断"
          - op_name: "清除状态"
            state: "自定义-星见雅使用过拔刀斩"

      - states: "([按键-切换角色-下一个,0,1]|[按键-切换角色-上一个,0,1])"
        sub_handlers:
          - states: "[雅-落霜]{6, 6}"
            operations:
              - operation_template: "雅-拔刀斩"

      - states: "[雅-落霜]{6, 6}"
        operations:
          - operation_template: "雅-拔刀斩合轴"

      - states: "[雅-终结技可用] & [雅-落霜]{0, 3}"
        operations:
          - operation_template: "雅-终结技"

      - states: "[自定义-星见雅使用过拔刀斩, 5, 30]"
        operations:
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]
          - operation_template: "雅-普通攻击"
          
      - states: "[雅-特殊技可用]"
        operations:
          - operation_template: "雅-特殊攻击"

      # 普通攻击
      - states: ""
        operations:
          - operation_template: "雅-普通攻击"