template_name: "速切模板-格莉丝"
handlers:
  - states: "[前台-格莉丝]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "通用-连携攻击"

      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
            - op_name: "清除状态"
              state: "自定义-动作不打断"

      - states: "[格莉丝-终结技可用]"
        operations:
          - op_name: "设置状态"
            state: "自定义-动作不打断"
          - op_name: "按键-终结技"
            post_delay: 2.5
            repeat: 2
          - op_name: "清除状态"
            state: "自定义-动作不打断"
            
        #格莉丝3段a1e
      - states: ""
        operations:
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
          - op_name: "按键-普通攻击"
            post_delay: 0.05
            repeat: 3
          - op_name: "按键-特殊攻击"
            post_delay: 0.1
          - op_name: "按键-普通攻击"
            post_delay: 0.05
            repeat: 3
          - op_name: "按键-移动-左"
            repeat: 3
