template_name: "速切模板-柏妮思"
handlers:
  - states: "[前台-柏妮思]"
    sub_handlers:
      - states: "[自定义-黄光切人, 0, 2]"
        sub_handlers:
          - state_template: "支援攻击模板-全角色"
      - states: "[自定义-连携换人,0,1]"
        operations:
          - operation_template: "柏妮思-连携攻击"

      - states: "([按键-切换角色-下一个,0,0.3]|[按键-切换角色-上一个,0,0.3]) | [自定义-快速支援换人,0,1]"
        operations:
          - op_name: "清除状态"
            state: "自定义-动作不打断"

      - states: "[柏妮思-终结技可用]"
        operations:
          - operation_template: "柏妮思-终结技"
      - states: "[柏妮思-燃点]{80,100} & ![柏妮思-特殊技可用]"
        operations:
          - operation_template: "柏妮思-长按普通攻击"
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]
      #有能量就一直把燃点到50以下          
      - states: "[柏妮思-燃点]{75,100}"
        operations:
          - operation_template: "柏妮思-长按普通攻击"
      - states: "[柏妮思-燃点]{51,100} & [柏妮思-特殊技可用]"
        operations:
          - op_name: "等待秒数"
            seconds: 0.2
          - operation_template: "柏妮思-长按普通攻击"
          - operation_template: "柏妮思-直接长按特殊攻击"
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]     
      - states: "[柏妮思-特殊技可用]"
        operations:
          - op_name: "等待秒数"
            seconds: 0.2
          - operation_template: "柏妮思-短按接长按特殊攻击"
          - op_name: "设置状态"
            data: [ "自定义-速切结束" ]
      - states: ""
        operations:
          - operation_template: "柏妮思-普通攻击"
