# 闪避普攻 普攻后摇等待时间各角色不同 由后续动作控制
handlers:
  - state_template: "闪A模板-青衣"

  #丽娜闪避支援很优秀
  - states: "![前台-丽娜]"
    sub_handlers:
    - states: "[丽娜-能量]{0, 120}"
      operations:
        - op_name: "按键-切换角色"
          agent_name: "丽娜"
        - op_name: "清除状态"
          state_list: ["自定义-速切结束", "自定义-动作不打断"]

  - state_template: "闪A模板-艾莲"
  - state_template: "闪A模板-柳"
  - state_template: "闪A模板-柏妮思"
  - state_template: "闪A模板-通用"
