project_name: "ZenlessZoneZero-OneDragon"
python_version: "3.11"
github_homepage: "https://github.com/OneDragon-Anything/ZenlessZoneZero-OneDragon"
github_https_repository: "https://github.com/OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
github_ssh_repository: "git@github.com:OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
gitee_https_repository: "https://gitee.com/OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
gitee_ssh_repository: "git@gitee.com:OneDragon-Anything/ZenlessZoneZero-OneDragon.git"
project_git_branch: "main"
requirements: "requirements-prod.txt"
screen_standard_width: 1920
screen_standard_height: 1080
pip_source: "https://pypi.tuna.tsinghua.edu.cn/simple"
qq_link: "https://qm.qq.com/q/wuVRYuZzkA"