name: "本-格挡"
auto_lock_interval: 0     # 关闭自动锁定
auto_turn_interval: 0     # 关闭自动转向
scenes:
- triggers: ["闪避识别-黄光", "闪避识别-红光", "闪避识别-声音"]
  interval: 0.5
  handlers:
  - states: "[闪避识别-黄光] | [闪避识别-红光] | [闪避识别-声音]"
    operations:
      - op_name: "按键-特殊攻击"
        data: []