scenes:
- triggers: ["闪避识别-黄光", "闪避识别-红光"]
  interval: 0.5
  handlers:
  - states: "[闪避识别-黄光] | [闪避识别-红光]"
    operations:
      - op_name: "按键-闪避"
        data: []
      - op_name: "等待秒数"
        data: ["0.2"]
      - op_name: "按键-普通攻击"
        data: []
