# 带雅, 然后绝境, 打不过就下一把.
# 该配置追求尽早通关, 所以BOSS房能进就进, 不能进就下一把.
# 建议难度低一点避免暴毙
# 反馈联系 IJDK
auto_battle: 全配队通用

region_type_priority:
- 战斗-武备
- 挑战-无伤
- 邦布商店
- 挚交会谈
- 战斗-道中危机
- 战斗-终结之役
- 战斗-硬币
- 战斗-鸣徽
- 挑战-限时

# 雅的全都要
# 凑机敏BUFF, 进一步强化无敌时间
# 其他角色活下来就行
artifact_priority:
- 星见雅
- 机敏 机敏蓄能盾
- 机敏 安全气囊
- 机敏 防护安全带
- 绝境
- 机敏 智能缓冲器
- 通用 BUG盾
- 终结 疗愈竖琴

buy_only_priority: 1

period_buff_no: 第一个