# 推荐配队: 强攻-击破-支援
# 战斗逻辑: 由击破站场打失衡，优先使用强攻格挡，失衡后切支援再切强攻进行爆发输出

check_dodge_interval: 0.02
check_agent_interval: [0.4, 0.6]
check_chain_interval: [0.9, 1.1]
check_quick_interval: [0.9, 1.1]
auto_lock_interval: 5

scenes:

  - triggers: [ "闪避识别-黄光", "闪避识别-红光", "闪避识别-声音" ]
    interval: 1
    handlers:
      - states: "![自定义-动作不打断, 0, 999]{1, 1} & [闪避识别-黄光]"
        sub_handlers:
          # 失衡期间 保持强攻在场上
          - states: "[自定义-连携换人, 0, 12]"
            sub_handlers:
              - states: "![前台-强攻]"
                state_template: "双反模板-强攻"
              - states: ""
                sub_handlers:
                  - state_template: "闪A模板-全角色"
          # 普通时间段
          - states: ""
            sub_handlers:
              - state_template: "双反模板-强攻"
              - state_template: "双反模板-击破"
              - state_template: "双反模板-下一个"
      - states: "![自定义-动作不打断, 0, 999]{1, 1} & ([闪避识别-红光] | [闪避识别-声音])"
        sub_handlers:
          - state_template: "闪A模板-全角色"

  - triggers: [ "按键可用-快速支援" ]
    interval: 1
    handlers:
      - states: "[按键可用-快速支援]"
        operations:
          - op_name: "按键-快速支援"
          - op_name: "设置状态"
            state: "自定义-快速支援换人"

  - triggers: [ "按键可用-连携技" ]
    interval: 1
    handlers:
      - states: "[按键可用-连携技]"
        sub_handlers:
          - state_template: "连携模板-强攻"
          - state_template: "连携模板-支援"
          - state_template: "连携模板-跳过"

  - triggers: [ "前台-血量扣减" ]
    interval: 2
    handlers:
      - states: "[前台-血量扣减]{1, 100} & ![自定义-动作不打断, 0, 999]"
        operations:
          # 由于每个角色的僵直不一样 由具体角色控制如何处理
          - op_name: "设置状态"
            state: "自定义-血量扣减"

  - triggers: [ ]
    interval: 0.02
    handlers:
      # 刚开始未识别到角色时候不要乱切
      - state_template: "站场模板-未识别角色"
      - states: "[自定义-黄光切人, 0, 2] | [自定义-红光闪避, 0, 2] | [自定义-临时站场]"
        sub_handlers:
          - state_template: "站场模板-全角色"
      - states: "[自定义-连携换人, 0, 12]"
        sub_handlers:
          - state_template: "站场模板-强攻站场"
      - state_template: "站场模板-击破站场"
      - state_template: "站场模板-强攻站场"
      - state_template: "站场模板-支援站场"
