operations:
  # 妮可向前滑+平A
  - op_name: "按键-移动-前"
    way: "按下"
  - op_name: "等待秒数"
    data: [ "0.2" ]
  - op_name: "按键-闪避"
    post_delay: 0.1
  - op_name: "按键-移动-前"
    way: "松开"
  - op_name: "按键-普通攻击"
    post_delay: 0.1
  # 切换比利 往前走再往右走
  - op_name: "按键-切换角色-下一个"
    post_delay: 0.5
  - op_name: "按键-移动-右"
    way: "按下"
    press: 3
  - op_name: "按键-移动-前"
    way: "按下"
    press: 3.2

  # 到尽头后 用闪避后退触发交互
  - op_name: "按键-闪避"
    post_delay: 0.5
